# Bob Tate
# 2/28/2021

# Constants - This file contains the constant values which can be adjusted to "tune" the difficulty of the game.

STARTING_HP = 100
STARTING_DISTANCE_TO_SHIP = 100
STARTING_SHIP_ATTACK = 5
STARTING_SHIP_ARMOR = 5
SNEAK_STEALTH = 10
RUN_STEALTH = 3
STEAL_STEALTH = 5
CH_ONE_BAD_GUY_STRENGTH = 3
CH_TWO_BAD_GUY_STRENGTH = 4
CH_TWO_ENEMY_STARTING_HP = 50
CH_TWO_PLUNDER_MULTIPLIER = 10
STORM_STRENGTH = 10
CREW_THIRST = 5
ATTACK_POINT_PRICE = 2
ARMOR_POINT_PRICE = 2
HP_PRICE = 1
CH_FIVE_ENEMY_STARTING_HP = 100
CH_FIVE_BAD_GUY_STRENGTH = 8
CH_FIVE_PLUNDER_MULTIPLIER = 20